
version: '3'
services:
  product-admin:
    image: "product-admin"
    container_name: product-admin
    ports:
     - "80:80"
    labels:
    - "productadmin"

  stuffmart:
    image: "stuffmart"
    container_name: stuffmart
    ports:
    - "8080:8080"